### ISSUE TITLE
hal wplist

### ISSUE THREAD

**Issue by technik** [grvcTeam/grvcQuadrotor#3]
Track wp list in hal. This functionality should be straight mapped to that of the backend.

**Comment by franreal** [comment]
We should define simple but flexible data types that will be used also by uav. Something like:

    struct Waypoint {
      Eigen::Vector3d position;
      double heading;
    };

    typedef std::vector<Waypoint> WaypointList;

**Comment by technik** [comment]
Take a look at the hal branch. I pushed it this morning, but haven't merged into master yet. I intended to make a couple more test before merging and try to build on ubuntu. https://github.com/grvcTeam/grvcQuadrotor/blob/hal/hal/include/grvc_quadrotor_hal/types.h

**Comment by technik** [comment]
I will also add the typedef for WaypointList. I think it is a good idea.

**Comment by franreal** [comment]
Magnifique!
